# Generated by Django 4.2.4 on 2023-10-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_recipe_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
